name: pediatricIQphantoms

channels:
  - conda-forge
  - defaults

dependencies:
  - octave
  - pandas
  - seaborn
  - tomli
  - numpy
  - matplotlib
  - oct2py
  - SimpleITK
  - pytest
  - sphinx-tabs
  - sphinxcontrib.inkscapeconverter
  - pip
  - pip:
    - "git+https://github.com/bnel1201/pediatricIQphantoms"
