name: pediatricIQphantoms

channels:
  - conda-forge
  - defaults

dependencies:
  - octave
  - pandas
  - tomli
  - numpy
  - oct2py
  - pytest
  - sphinx-tabs
  - pandoc
  - ipykernel
  - pip
  - pip:
    - "git+https://github.com/brandonjnelsonFDA/pediatricIQphantoms"
    - sphinxcontrib-svg2pdfconverter
    - nbsphinx
