# test.toml
[[simulation]]

# directories
image_directory = "results/test"
# filetype = '.mhd' # mhd for metaheader or dcm for dicom
# phantoms
model = ['MITA-LCD', 'CTP404'] # <-- current options include ['CTP404', 'MITA-LCD', 'UNIFORM']
diameter = [112, 292] # <-- units in mm
reference_diameter = 200 # <-- diameter in mm of the real physcial phantom for comparison

# acquisition
framework = "MIRT"
nsims = 2 # <-- number of simulations to perform with different noise instantiations
aec_on = true # (aec built in to ped xcat) <-- 'aec' = automatic exposure control, when `true`, it ensures constant noise levels for all `patient_diameters` (see `reference_dose_level` for more info)
add_noise = true # <-- if true adds Poisson noise, noise magnitude set by `reference_dose_level`, noise texture set by reconstructed field of view (cuttently fov = 110# patient_diameter) 
full_dose = 3e5 # <-- units of photons per pixel
dose_level = [0.25, 1.00] # <-- units of photons, this expression is evaluated by matlab, so keep in this format '[xx, yy, zz]'

# acquisition geometry # CT geometry (the following parameter values simulate Siemens Force) 
sid = 595          #(mm) source-to-isocenter distance (value based on AAPM LDCT data dicom header)
sdd = 1085.6          # source-to-detector distance
# isocenter-to-detector distance dod = sdd - sid 

nb = 880           # number of detector columns (set it to be large enough to cover the projected FOV to avoid truncation)
nangles = 100          # number of views in a rotation
                      # (na=1160 based on ZengEtAl2015-IEEE-NuclearScience-v62n5:"A Simple Low-Dose X-Ray CT Simulation From High-Dose Scan")
                      
ds = 1        # detector column size 
offset_s = 1.25    # lateral shift of detector

# reconstruction

fov = 340  # <-- FOV in mm of adult protocol used in scanning real physical phantom for comparison
image_matrix_size = 256 # <-- reconstructed matrix size in pixels (square, equal on both sides)
fbp_kernel = 'hanning,2.05' # 'hanning,xxx', xxx = the cutoff frequency, see fbp2_window.m in MIRT for details.
                        #'hanning,2.05' approximate a sharp kernel D45 in Siemens Force.
                        #'hanning,0.85' approximate a smooth kernel B30 in
                        #Siemens Force.
