name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    # from https://github.com/marketplace/actions/setup-miniconda#example-3-other-options
    - uses: conda-incubator/setup-miniconda@v3
    - name: Set up conda with Python 3.10
      uses: actions/setup-python@v3
      with:
        activate-environment: octave
        environment-file: environment.yml
        python-version: '3.10'
        auto-activate-base: false
    - name: Install dependencies
      run: |
        conda activate octave
        # install local package
        pip install .
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
